# Starship configuration
# https://starship.rs/config/

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = "[$directory$git_branch$git_status]($style)$character"

palette = 'catppuccin_mocha'
# palettes
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
orange = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[character]
error_symbol = "[âœ—](bold yellow)"
success_symbol = "[â¯](bold yellow)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
truncation_length = 2
truncation_symbol = "â€¦/"
repo_root_style = "bold teal"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "[$branch]($style) "
style = "italic red"

[git_status]
format     = '[$all_status]($style)'
style      = "blue"
ahead      = "â‡¡${count} "
diverged   = "â‡•â‡¡${ahead_count}â‡£${behind_count} "
behind     = "â‡£${count} "
conflicted = "î®«"
up_to_date = "ï€Œ "
untracked  = "?"
modified   = "î©±"
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""

[nodejs]
format = 'via [ğŸ¤– $version](bold green) '

[python]
format = 'via [ğŸ $version](bold green) '

[golang]
format = 'via [ğŸ¹ $version](bold green) '

[rust]
format = 'via [ğŸ¦€ $version](bold green) '

[docker_context]
format = 'via [ğŸ³ $context](bold blue) '

[kubernetes]
format = 'via [â˜¸ï¸ $context](bold blue) '

[aws]
format = 'via [â˜ï¸ $profile](bold yellow) '

[time]
disabled = false
format = 'ğŸ•™ $time($style) '
time_format = '%T'
utc_time_offset = 'local'
